In [1]:
import numpy as np

In [3]:
arr = np.arange(0,11+1)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
trozoArr = arr[0:6]

In [7]:
trozoArr

array([0, 1, 2, 3, 4, 5])

In [12]:
trozoArr[:] = 0
trozoArr



array([0, 0, 0, 0, 0, 0])

In [16]:
# Solucionar la cagada que acabamos de hacer en el array XD 
arr_copy = arr.copy()

arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [17]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10, 11])

In [21]:
# Resumen:
#! Al usar copy usaremos una copia del array original 
matriz = np.array([[1, 2, 3], [4, 5, 6]])

# Haciendo la copia de nuestro matriz original para manipularlo a nuestro antojo
matriz2 = matriz.copy()

matriz2[:] = 100230203
matriz2



array([[100230203, 100230203, 100230203],
       [100230203, 100230203, 100230203]])

In [24]:
matriz

print()

matriz2

array([[100230203, 100230203, 100230203],
       [100230203, 100230203, 100230203]])