In [1]:
import numpy as np

In [2]:
# Hacer un retorno de datos un poco mas especificos o que cumplan cosas muy puntuales

arr = np.linspace(1,10,10, dtype="int8")
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [6]:
arr3 = []
for i in arr:
    if i > 5: 
        arr3.append(i)
        

print(arr3)

[6, 7, 8, 9, 10]


In [8]:
#
#! Usando la libreria de python
verdaderosIndices = arr > 5 
arr[verdaderosIndices]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [10]:
# Haciendo muchas mas condicionales
arr5 = np.arange(0, 10+1)

arr5[(arr5 > 2) & (arr5 < 9)]

array([3, 4, 5, 6, 7, 8])

In [11]:
#
#! Operaciones y como aplicarlas a nuestros array's 
lista = [1,2]
lista

[1, 2]

In [12]:
lista * 2
# Esto es erroneo

[1, 2, 1, 2]

In [13]:
arr7 = np.arange(0, 11)
arr7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
arr10 = arr7.copy() 

# Realizando operaciones aritmeticas 
arr7 * 2 


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
listData = np.arange(0, 11)
listData
 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [20]:
listData * 2 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [23]:
1 / listData

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_6204\3567396952.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / listData


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])