In [1]:
import numpy as np

# Pruebas y ejercicios con numpy

In [2]:
# Crear una lista del 1-20
ejer1 = np.arange(1, 21)
ejer1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [3]:
# Ejercicio 2, con la siguiente lista hace otra con solo elementos impares 
arr = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50])


In [4]:
arrImpares = arr.copy()


In [6]:
data = []
for i in arrImpares:
    if i % 2 == 1: 
        data.append(i)
        
        
print(f"Numeros impares del array: \n{arr}\n\nNumeros impares: {data}")

Numeros impares del array: 
[ 5 10 15 20 25 30 35 40 45 50]

Numeros impares: [5, 15, 25, 35, 45]


In [7]:
# Con el siguiente array, verificar que numeros son menores o igual que 12
matriz1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matriz2 = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])


In [10]:
numsMatriz1 = matriz1[matriz1 <= 12]
numsMatriz2 = matriz2[matriz2 <= 12]


print(f"Dadas las siguientes matrices: \n\n{matriz1}\n{matriz2}\n\nLos numeros menores o igual a 12 son: \n{numsMatriz1}\n{numsMatriz2}")

Dadas las siguientes matrices: 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Los numeros menores o igual a 12 son: 
[1 2 3 4 5 6 7 8 9]
[ 2  4  6  8 10 12]


In [11]:
# Suma de matrices con numpy 

matriz1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matriz2 = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])

matriz3 = matriz1 + matriz2
matriz3

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [12]:
np.array([[1,2,3],[4,5,6],[7,8,9]]).ndim

2