In [1]:
# Tomando un repaso tanto de numpy como de pandas 
import numpy as np 
import pandas as pd

### Creacion de arrays y DataFrames

In [3]:
# Creacion de arrays y "dataFrames"
np.linspace(10, -10)


array([ 10.        ,   9.59183673,   9.18367347,   8.7755102 ,
         8.36734694,   7.95918367,   7.55102041,   7.14285714,
         6.73469388,   6.32653061,   5.91836735,   5.51020408,
         5.10204082,   4.69387755,   4.28571429,   3.87755102,
         3.46938776,   3.06122449,   2.65306122,   2.24489796,
         1.83673469,   1.42857143,   1.02040816,   0.6122449 ,
         0.20408163,  -0.20408163,  -0.6122449 ,  -1.02040816,
        -1.42857143,  -1.83673469,  -2.24489796,  -2.65306122,
        -3.06122449,  -3.46938776,  -3.87755102,  -4.28571429,
        -4.69387755,  -5.10204082,  -5.51020408,  -5.91836735,
        -6.32653061,  -6.73469388,  -7.14285714,  -7.55102041,
        -7.95918367,  -8.36734694,  -8.7755102 ,  -9.18367347,
        -9.59183673, -10.        ])

In [7]:
np.zeros()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
# Creando matricez de datos con numpy
matriz = np.zeros((3,3))
matriz

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Atributos de un array

In [9]:
# Devolviendo las dimensiones de estructuras ya creadas 
dimension_matriz = np.ndim(matriz)
print(f"La dimension de la matriz anteriormente creada es de: {dimension_matriz}")

La dimension de la matriz anteriormente creada es de: 2


In [10]:
# Numero de elemnteos dentro de un array
num_elementos = np.size(matriz)
print(f"El numero de elementos dentro de la matriz: \n\n{matriz}\n\nEs de: {num_elementos}")

El numero de elementos dentro de la matriz: 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Es de: 9


In [16]:
# Realizando condicionales dentro de un array de numpy 
array1 = np.array([i for i in np.arange(1, 20+1)])
print(f"Datos totales dentro de un array: \n{array1}")

print(f"\nFiltrando por numeros pares: \n{array1[array1 % 2 ==0]}")

Datos totales dentro de un array: 
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Filtrando por numeros pares: 
[ 2  4  6  8 10 12 14 16 18 20]


#### Solucionando un sistema de ecuaciones con numpy

In [18]:
# Sistema de dos ecuaciones y dos incógnitas
# x + 2y = 1
# 3x + 5y = 2 

lines = np.array([[1,2], [3,5]])
results = np.array([1,2])
print(f"La solucion de las incognitas es: {np.linalg.solve(lines, results)}")



La solucion de las incognitas es: [-1.  1.]


In [20]:
# Otro sistema de ecuaciones 
# x +y = 7
# 5x -2y = -7 

lines2 = np.array([[1,1], [5, -2]])
responses = np.array([7, -7])
np.linalg.solve(lines2, responses)

array([1., 6.])